Added parameter for message priority
austineric/Send-MailKitMessage pull request #27
Opened 2022-08-29 09:39 UTC by mayka-mack

Added new optional parameter `-Priority` for setting the message priority as `NonUrgent` (0), `Normal` (1), or `Urgent` (2).

Included `Low` and `High` as aliases for `NonUrgent` and `Urgent` respectively, as the now deprecated `Send-MailMessage` Cmdlet uses `Low`, `Normal`, and `High` for message priority.

2022-08-29 19:57 UTC, austineric commented on Project/Send-MailKitMessage.csproj
> +    <FileVersion>3.2.0.12</FileVersion>
These changes can be removed, these values get set during the NuGet publish process

2022-08-29 19:58 UTC, austineric commented on README.md
> +
This change can be removed, a couple other updates need to be made before release 3.2.0-preview2

2022-08-29 20:03 UTC, austineric requested changes
Hi @mayka-mack,
Thanks for the pr!
It looks good, very thorough.
I left a couple of comments on things I am requesting be removed (around versioning etc since those are set automatically).
If you can commit those changes it should update this pr automatically (https://github.com/github/hub/issues/198) and I can approve.

2022-08-30 11:10 UTC, mayka-mack commented
> Hi @mayka-mack, Thanks for the pr! It looks good, very thorough. I left a couple of comments on things I am requesting be removed (around versioning etc since those are set automatically). If you can commit those changes it should update this pr automatically ([github/hub#198](https://github.com/github/hub/issues/198)) and I can approve.

These should now be updated. Will keep that in mind for the future!

2022-08-30 17:38 UTC, austineric commented
Looks good, merging into a new branch 3.2.0-preview2 in order to incorporate a couple other small changes.
Thanks!

2022-08-30 17:40 UTC, merged